[package]
name = "snake-tui"
version = "0.1.0"
authors = ["ivan tkachenko <me@ratijas.tk>"]
description = "Snake game in a terminal"

[dependencies]

snake-lib = { path = "../snake-lib", features = ["pancurses"] }
pancurses = "0.7"
